"""
Compute opening and event frequencies from PGN files and write src/frequencies.py.

Usage (run from project root):
    python scripts/compute_freqs.py [pgn_glob]

Default glob: data/input/*.pgn
"""

import re
import glob
import sys
from collections import Counter
from pathlib import Path

HEADER_RE = re.compile(r'\[(\w+)\s+"([^"]*)"\]')
OUT_PATH   = Path(__file__).parent.parent / "src" / "frequencies.py"


def count_freqs(pattern: str) -> tuple[Counter, Counter]:
    opening_counts: Counter = Counter()
    event_counts:   Counter = Counter()
    files = sorted(glob.glob(pattern))
    if not files:
        sys.exit(f"No files matched: {pattern}")
    for path in files:
        with open(path, encoding="utf-8") as f:
            for line in f:
                m = HEADER_RE.match(line.strip())
                if not m:
                    continue
                tag, value = m.group(1), m.group(2)
                if tag == "Opening":
                    opening_counts[value] += 1
                elif tag == "Event":
                    event_counts[value] += 1
    return opening_counts, event_counts


def write_freqs(opening_counts: Counter, event_counts: Counter) -> None:
    lines = [
        "# Auto-generated by scripts/compute_freqs.py — do not edit by hand.",
        "# Rerun that script against data/input/*.pgn to refresh.",
        "# Counts come from the training PGN corpus; used to build Huffman trees",
        "# in openings.py and constant_types.py.",
        "",
        "# symbol -> occurrence count; UNKNOWN_TEXT covers anything not in the list.",
        "",
        "OPENING_FREQS: dict[str, int] = {",
    ]
    for s, c in opening_counts.most_common():
        lines.append(f"    {s!r}: {c},")
    lines.append("    'UNKNOWN_TEXT': 1,")
    lines.append("}")
    lines.append("")
    lines.append("EVENT_FREQS: dict[str, int] = {")
    for s, c in event_counts.most_common():
        lines.append(f"    {s!r}: {c},")
    lines.append("    'UNKNOWN_TEXT': 1,")
    lines.append("}")
    lines.append("")

    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    pattern = sys.argv[1] if len(sys.argv) > 1 else "data/input/*.pgn"
    opening_counts, event_counts = count_freqs(pattern)
    write_freqs(opening_counts, event_counts)
    print(f"Written {OUT_PATH}")
    print(f"  {len(opening_counts)} opening entries  ({sum(opening_counts.values())} total)")
    print(f"  {len(event_counts)} event entries  ({sum(event_counts.values())} total)")
