import bitarray as bitLib

# 1608 unique Opening values from the dataset, ordered by frequency.
# Encoding: 11 bits per value (covers indices 0–2046).
# Index 2047 (all 1s) = UNKNOWN_TEXT sentinel — raw UTF-8 follows.

OPENING_BITS    = 11
OPENING_UNKNOWN = (1 << OPENING_BITS) - 1   # 2047

_OPENING_STRINGS = [
    "Van't Kruijs Opening",
    'Modern Defense',
    'Scandinavian Defense: Mieses-Kotroc Variation',
    'Horwitz Defense',
    'Sicilian Defense',
    'French Defense: Knight Variation',
    'Scandinavian Defense',
    'Caro-Kann Defense',
    'Philidor Defense #3',
    'Owen Defense',
    "Queen's Pawn Game #2",
    'Sicilian Defense: Bowdler Attack',
    'Hungarian Opening',
    "Queen's Pawn Game: Chigorin Variation",
    "Queen's Pawn",
    'Philidor Defense #2',
    "Bishop's Opening",
    'French Defense: Normal Variation',
    'Sicilian Defense: Old Sicilian',
    'Indian Game',
    "King's Pawn Game: Leonardis Variation",
    'Pirc Defense #4',
    "King's Pawn Game: Wayward Queen Attack",
    'Scotch Game',
    "Queen's Pawn Game: Zukertort Variation",
    "Queen's Pawn Game",
    "Queen's Pawn Game: Mason Attack",
    'Italian Game: Anti-Fried Liver Defense',
    'Sicilian Defense: McDonnell Attack',
    'Mieses Opening',
    "Bishop's Opening: Berlin Defense",
    "Queen's Gambit Declined",
    'Old Benoni Defense',
    'French Defense #2',
    'English Defense #2',
    'French Defense: Exchange Variation',
    'Bird Opening',
    'Italian Game',
    'Ruy Lopez: Steinitz Defense',
    'Sicilian Defense: Alapin Variation',
    'Robatsch (Modern) Defense',
    'Four Knights Game: Italian Variation',
    'Rat Defense: Small Center Defense',
    'Sicilian Defense: Smith-Morra Gambit #2',
    "Queen's Gambit Refused: Marshall Defense",
    "King's Pawn Game: McConnell Defense",
    "King's Pawn Game",
    'Scandinavian Defense: Modern Variation #2',
    "French Defense: Queen's Knight",
    "Queen's Gambit Accepted",
    'Scandinavian Defense: Main Line',
    'Slav Defense #2',
    'Russian Game: Three Knights Game',
    'French Defense: La Bourdonnais Variation',
    'Philidor Defense',
    "King's Pawn Game: Busch-Gass Gambit",
    "Queen's Gambit Accepted: Old Variation",
    "Queen's Pawn Game #3",
    'Russian Game: Urusov Gambit',
    'Three Knights Opening',
    'Sicilian Defense: French Variation',
    "King's Gambit",
    'Philidor Defense: Exchange Variation #2',
    'Giuoco Piano',
    'Sicilian Defense: Closed Variation',
    'Saragossa Opening',
    'Zukertort Opening: Tennison Gambit',
    "King's Pawn Game: Napoleon Attack",
    'Bird Opening: Dutch Variation',
    "King's Knight Opening: Normal Variation",
    "King's Knight Opening",
    "Bishop's Opening: Boi Variation",
    'Nimzo-Larsen Attack',
    'St. George Defense',
    "English Opening: King's English Variation",
    '?',
    "French Defense: King's Indian Attack",
    'English Opening: Agincourt Defense',
    'French Defense: Advance Variation #3',
    "Italian Game: Two Knights Defense, Modern Bishop's Opening",
    'Polish Opening',
    'Pirc Defense #5',
    'Elephant Gambit',
    'Center Game #2',
    'Englund Gambit Declined, Reversed French',
    'Caro-Kann Defense: Exchange Variation',
    'Caro-Kann Defense: Advance Variation',
    'Nimzowitsch Defense',
    'Englund Gambit',
    'Dutch Defense',
    'Vienna Game',
    "Queen's Pawn Game: London System",
    'Sicilian Defense: Nyezhmetdinov-Rossolimo Attack',
    "Queen's Pawn Game: Levitsky Attack",
    'Zukertort Opening: Sicilian Invitation',
    "English Opening: King's English Variation, Reversed Sicilian",
    "Queen's Gambit Declined: Queen's Knight Variation",
    "King's Gambit Declined, Queen's Knight Defense",
    'Anderssen Opening',
    "Zukertort Opening: Queen's Gambit Invitation",
    'Nimzo-Larsen Attack: Classical Variation',
    'Danish Gambit',
    'Ruy Lopez: Berlin Defense #2',
    'Old Indian Defense',
    'Van Geet Opening',
    'Sicilian Defense: Closed Variation, Traditional',
    "King's Gambit Accepted, King's Knight Gambit",
    'French Defense: Steinitz Attack',
    'Grob Opening',
    'English Opening',
    'Sicilian Defense: Open #3',
    'Nimzowitsch Defense: Kennedy Variation, Linksspringer Variation',
    'Semi-Slav Defense: Accelerated Move Order',
    'Sicilian Defense: Najdorf Variation',
    "King's Pawn Game: Macleod Attack",
    "King's Pawn Game: Maroczy Defense",
    'English Opening: The Whale',
    'English Opening: Anglo-Scandinavian Defense',
    'Scotch Game: Classical Variation',
    'Center Game: Normal Variation',
    "King's Pawn Game: Damiano Defense",
    "King's Gambit Accepted, Fischer Defense",
    "Queen's Pawn Game: Symmetrical Variation",
    'Italian Game: Giuoco Pianissimo, Normal',
    'Mikenas Defense',
    'Alekhine Defense',
    'Nimzowitsch Defense: Scandinavian Variation, Advance Variation',
    'Sicilian Defense: Delayed Alapin',
    'Zukertort Opening: Kingside Fianchetto',
    'French Defense: Advance Variation, Nimzowitsch System',
    'Slav Defense',
    'Caro-Kann Defense: Hillbilly Attack',
    'Sicilian Defense: Open',
    'English Opening: Great Snake Variation',
    'Alekhine Defense: Maroczy Variation',
    'French Defense: Advance Variation #2',
    'Sicilian Defense: Loewenthal Variation',
    "King's Gambit Accepted, MacLeod Defense",
    "Queen's Gambit Declined: Normal Defense",
    'Nimzo-Larsen Attack: Modern Variation #2',
    'Sicilian Defense: Staunton-Cochrane Variation',
    "King's Pawn",
    'Sicilian Defense #2',
    'Reti Opening',
    'Sicilian Defense: Paulsen Variation',
    'Ware Opening',
    "King's Pawn Game: Wayward Queen Attack, Kiddie Countergambit",
    'Benoni Defense: Benoni Gambit Accepted',
    'French Defense: Advance Variation, Paulsen Attack',
    'Kadas Opening',
    'Sicilian Defense: Smith-Morra Gambit',
    "Queen's Pawn Game: Colle System",
    'Ponziani Opening: Jaenisch Counterattack',
    "King's Indian Attack",
    'Alekhine Defense: Scandinavian Variation',
    'Italian Game: Schilling-Kostic Gambit',
    "Queen's Gambit Declined: Three Knights Variation",
    'Vienna Game: Stanley Variation',
    'Ruy Lopez: Bird Variation',
    'Colle System',
    'Zukertort Opening: Pirc Invitation',
    'Semi-Slav Defense',
    "Petrov's Defense",
    'Caro-Kann Defense: Advance Variation, Short Variation',
    'Ruy Lopez',
    "Queen's Gambit",
    'Ruy Lopez: Classical Variation',
    'Hungarian Opening: Slav Formation',
    'Caro-Kann Defense: Breyer Variation',
    'Slav Defense: Three Knights Variation',
    'Pirc Defense',
    "Petrov's Defense #2",
    'Philidor Defense #4',
    'Vienna Game: Max Lange Defense',
    'Sicilian Defense: Closed',
    "Queen's Gambit Refused: Albin Countergambit",
    "Queen's Pawn Game: Franco-Sicilian Defense",
    'Philidor Defense: Exchange Variation',
    'Ruy Lopez: Exchange Variation',
    "Bishop's Opening: Philidor Counterattack",
    "King's Pawn Game: Nimzowitsch Defense",
    'English Opening: Symmetrical Variation',
    'Pirc Defense: Classical Variation',
    "Queen's Pawn Game: Krause Variation",
    'Four Knights Game',
    'Scandinavian Defense: Gubinsky-Melts Defense',
    'Zukertort Opening: Black Mustang Defense',
    "English Opening: King's English Variation, Two Knights Variation",
    'Rat Defense: Harmonist',
    'French Defense: Rubinstein Variation',
    'French Defense: Advance Variation',
    "Queen's Pawn Game: Anti-Torre",
    'Italian Game: Giuoco Pianissimo',
    'Ponziani Opening',
    'Semi-Slav Defense: Main Line',
    'Center Game: Paulsen Attack Variation',
    'Philidor Defense: Exchange Variation #3',
    'Italian Game: Two Knights Defense, Fried Liver Attack',
    'Reti Opening #2',
    'Indian Game: East Indian Defense',
    'Caro-Kann Defense: Two Knights Attack',
    'English Opening: Anglo-Indian Defense',
    'Ruy Lopez: Cozio Defense',
    'Slav Defense: Modern Line',
    'Hungarian Opening: Symmetrical Variation',
    "Gedult's Opening",
    'English Opening: Caro-Kann Defensive System',
    'Carr Defense',
    "King's Pawn Opening: 2.b3",
    'Slav Defense: Exchange Variation',
    "English Opening: Anglo-Indian Defense, Queen's Knight Variation",
    "King's Indian Defense: Normal Variation, Rare Defenses",
    'Four Knights Game: Spanish Variation, Classical Variation',
    'Italian Game: Giuoco Pianissimo, Italian Four Knights Variation',
    'Scotch Game: Scotch Gambit',
    'French Defense: Exchange Variation, Monte Carlo Variation',
    'Four Knights Game: Spanish Variation',
    'Italian Game: Two Knights Defense, Knight Attack, Normal Variation',
    'Italian Game: Two Knights Defense',
    'Zukertort Opening: Old Indian Attack',
    'French Defense: Advance Variation #4',
    'Nimzowitsch Defense: Franco-Nimzowitsch Variation',
    'Trompowsky Attack',
    'Mieses Opening: Reversed Rat',
    "King's Gambit Accepted, Schallopp Defense",
    'Four Knights Game: Scotch Variation Accepted',
    'Elephant Gambit: Paulsen Countergambit',
    "King's Pawn Game: King's Head Opening #2",
    'Sicilian Defense: Kan Variation, Knight Variation',
    'French Defense: Steiner Variation',
    'Caro-Kann Defense: Advance Variation, Botvinnik-Carls Defense',
    'Center Game',
    'Nimzo-Indian Defense: Ragozin Variation',
    'Franco-Benoni Defense',
    'English Defense',
    'Clemenz Opening',
    "King's Gambit Accepted, Cunningham Defense",
    'Indian Game: Budapest Defense',
    'Sicilian Defense: Accelerated Dragon, Modern Variation',
    "Queen's Gambit Accepted: Saduleto Variation",
    'Benoni Defense',
    'Italian Game: Hungarian Defense',
    'Hungarian Opening: Catalan Formation',
    "King's Indian Defense",
    'Modern Defense: Two Knights Variation',
    'Benoni Defense: Old Benoni',
    'Duras Gambit',
    'Caro-Kann Defense: Classical Variation',
    "Queen's Gambit Refused: Baltic Defense",
    'Sicilian Defense: Hyperaccelerated Dragon',
    'Torre Attack #2',
    'Ware Defense',
    "Dutch Defense: Queen's Knight Variation",
    'Italian Game: Classical Variation, Giuoco Pianissimo',
    'Scotch Game: Schmidt Variation',
    'English Opening: Symmetrical Variation, Normal Variation',
    'Nimzo-Larsen Attack: Modern Variation #3',
    'Nimzo-Larsen Attack: English Variation',
    'Nimzowitsch Defense, Declined Variation',
    "English Opening: King's English Variation, Reversed Closed Sicilian",
    'Sicilian Defense: Lasker-Dunne Attack',
    'French Defense: Two Knights Variation',
    'Hungarian Opening: Sicilian Invitation',
    'Sicilian Defense: Delayed Alapin Variation',
    'Sicilian Defense: Grand Prix Attack',
    'East Indian Defense',
    "Queen's Gambit Declined: Exchange Variation",
    'Zukertort Opening: Queenside Fianchetto Variation',
    'Caro-Kann Defense #2',
    'Van Geet Opening: Reversed Nimzowitsch',
    'Scandinavian Defense: Blackburne Gambit',
    'French Defense: Paulsen Variation',
    'Modern Defense: Standard Line',
    'Budapest Defense: Adler Variation',
    'Sicilian Defense: Paulsen Variation, Normal Variation',
    'Old Benoni Defense #2',
    "Queen's Gambit Declined: 4.Bg5 Be7",
    'Goldsmith Defense',
    "Queen's Pawn Game: Symmetrical Variation, Pseudo-Catalan",
    "Queen's Gambit Refused: Austrian Defense",
    'Alekhine Defense: Normal Variation',
    'Ruy Lopez: Morphy Defense, Anderssen Variation',
    "Queen's Gambit Declined: Modern Variation",
    'Hungarian Opening: Indian Defense',
    'Scotch Game: Haxo Gambit',
    'Vienna Game: Anderssen Defense',
    'Russian Game: Damiano Variation',
    'Blackmar-Diemer Gambit',
    'Latvian Gambit',
    'Alekhine Defense: John Tracy Gambit',
    'Modern Defense: Three Pawns Attack',
    'Reti Opening: Reti Accepted',
    'London System',
    'Nimzo-Larsen Attack: Modern Variation #4',
    'Modern Defense: Mongredien Defense #2',
    'Sicilian Defense: Canal Attack, Main Line',
    "Queen's Gambit Accepted: Accelerated Mannheim Variation",
    'Sicilian Defense: Snyder Variation',
    'Nimzo-Larsen Attack: Indian Variation',
    'Englund Gambit Complex: Hartlaub-Charlick Gambit',
    'French Defense: Marshall Variation',
    'Indian Game: Wade-Tartakower Defense',
    'Nimzo-Indian Defense',
    'French Defense: Classical Variation, Steinitz Variation',
    'Italian Game: Classical Variation #2',
    'Sicilian Defense: Classical Variation',
    "King's Indian Defense: Normal Variation, King's Knight Variation",
    'Ruy Lopez: Morphy Defense, Caro Variation',
    'Sicilian Defense: Open #2',
    'Scandinavian Defense: Main Line, Mieses Variation',
    "King's Gambit Accepted: Modern Defense #2",
    "Bird Opening: From's Gambit",
    'Italian Game: Classical Variation, Albin Gambit',
    'Four Knights Game: Scotch Variation',
    'Rat Defense: English Rat',
    'Nimzowitsch Defense: Scandinavian Variation, Exchange Variation',
    'Paleface Attack',
    'Sicilian Defense: Modern Variations, Main Line',
    'Englund Gambit Complex Declined',
    'Benoni Defense: Hromadka System',
    'Vienna Game: Vienna Gambit',
    'Indian Game: Anti-Nimzo-Indian',
    'Pirc Defense #2',
    'Richter-Veresov Attack',
    'Sicilian Defense: Nyezhmetdinov-Rossolimo Attack, Fianchetto Variation',
    "Queen's Pawn Game: Stonewall Attack",
    'Vienna Game: Stanley Variation, Reversed Spanish',
    'Vienna Game: Falkbeer Variation',
    'Alekhine Defense #2',
    'Tarrasch Defense',
    'Alekhine Defense: Exchange Variation',
    "Modern Defense: Geller's System",
    'Nimzowitsch Defense: Williams Variation',
    'Caro-Kann Defense: Accelerated Panov Attack #2',
    'Tarrasch Defense: Symmetrical Variation',
    'Philidor Defense: Hanham Variation',
    'Nimzo-Indian Defense: Three Knights Variation',
    'Barnes Defense',
    'Scandinavian Defense: Marshall Variation',
    'Sicilian Defense: Marshall Counterattack',
    'French Defense: Advance Variation, Euwe Variation',
    'Pirc Defense #3',
    'Scandinavian Defense: Panov Transfer',
    "King's Indian Defense: Six Pawns Attack",
    'Nimzo-Indian Defense #2',
    'Modern Defense: Standard Defense',
    'Latvian Gambit Accepted',
    'Torre Attack',
    "Queen's Pawn Game: Veresov Attack, Alburt Defense",
    'Sicilian Defense: Hyperaccelerated Fianchetto',
    'Slav Defense: Quiet Variation, Pin Defense',
    'Sicilian Defense: Dragon Variation',
    'Sicilian Defense: Najdorf, Lipnitsky Attack',
    'Sicilian Defense: Najdorf Variation, English Attack',
    'Owen Defense: Smith Gambit',
    "Sicilian Defense: O'Kelly Variation, Normal System",
    'Nimzo-Larsen Attack: Modern Variation',
    'Indian Game: Pawn Push Variation',
    'Caro-Kann Defense: Panov Attack #2',
    'French Defense: Mediterranean Defense',
    'Colle System #2',
    "Queen's Pawn Game: Torre Attack",
    'Rat Defense: Antal Defense',
    'Indian Game: London System',
    'Modern Defense: Averbakh Variation',
    'Indian Game: Spielmann-Indian',
    'English Opening: Anglo-Indian Defense, Hedgehog System',
    'Ruy Lopez: Exchange Variation, Lutikov Variation',
    'Alekhine Defense: Two Pawn Attack',
    'Sicilian Defense: French Variation, Open',
    'Sicilian Defense: Franco-Sicilian Variation',
    "Queen's Gambit Declined: Harrwitz Attack",
    'English Opening: Carls-Bremen System',
    'Dutch Defense: Rubinstein Variation',
    'Sicilian Defense: Najdorf Variation, Opocensky Variation',
    'Center Game: Berger Variation',
    "Queen's Gambit Accepted: Normal Variation",
    'Englund Gambit Complex: Englund Gambit',
    'Borg Defense',
    'Italian Game: Two Knights Defense, Polerio Defense, Bishop Check Line',
    'Caro-Kann Defense: Maroczy Variation',
    'Sicilian Defense: Katalimov Variation',
    'Zukertort Opening: Reversed Mexican Defense',
    'Russian Game: Cozio (Lasker) Attack',
    'French Defense: Tarrasch Variation, Closed Variation',
    'Indian Game: Tartakower Attack',
    'French Defense: Horwitz Attack, Papa-Ticulat Gambit',
    'Scotch Game: Benima Defense',
    'Caro-Kann Defense: Main Line',
    'French Defense: Advance Variation, Milner-Barry Gambit',
    'Sicilian Defense: Chekhover Variation',
    'Polish Opening: Czech Defense',
    "Queen's Gambit Accepted: Central Variation, Greco Variation",
    "Queen's Gambit Refused: Chigorin Defense #2",
    'Sicilian Defense: Accelerated Dragon',
    'Ruy Lopez: Berlin Defense, Beverwijk Variation',
    'Scotch Game: Goering Gambit, Double Pawn Sacrifice',
    'Dutch Defense: Classical Variation',
    'Sicilian Defense: Kramnik Variation',
    'Slav Defense #3',
    'Scotch Game: Classical Variation, Intermezzo Variation',
    'Italian Game: Two Knights Defense, de Riviere Gambit',
    'Zukertort Opening: Slav Invitation',
    'Benoni Defense: Modern Variation',
    'Vienna Game: Zhuravlev Countergambit #2',
    'Four Knights Game: Gunsberg Variation',
    'Amazon Attack',
    'Italian Game: Two Knights Defense, Knight Attack',
    'Nimzo-Indian Defense: Leningrad Variation',
    "Queen's Gambit Declined: Modern Variation, Normal Line",
    'Three Knights Opening #2',
    "Queen's Gambit Accepted: Rosenthal Variation",
    'French Defense: Horwitz Attack',
    'Gunderam Defense',
    'Scandinavian Defense: Icelandic-Palme Gambit',
    "Queen's Gambit Declined: Vienna Variation",
    'Indian Game: Seirawan Attack',
    'Nimzo-Larsen Attack: Symmetrical Variation',
    'Indian Game: West Indian Defense',
    'English Opening: Anglo-Dutch Defense',
    "Queen's Pawn Game: Veresov Attack, Classical Defense",
    'Danish Gambit Accepted, Copenhagen Defense',
    "Queen's Gambit Refused: Chigorin Defense",
    "Sicilian Defense: O'Kelly Variation",
    'Philidor Defense: Lion Variation',
    'Tarrasch Defense: Two Knights Variation',
    'French Defense: Tarrasch Variation',
    'Russian Game: Modern Attack, Symmetrical Variation #2',
    'Polish Defense',
    "Queen's Pawn Game: Steinitz Countergambit",
    'Reti Opening: Advance Variation',
    'Englund Gambit Complex: Soller Gambit',
    'Slav Defense: Modern',
    "King's Pawn Game: Tayler Opening",
    "King's Indian Defense: Orthodox Variation",
    'English Opening: Symmetrical Variation, Two Knights Variation',
    "King's Gambit Accepted, Becker Defense",
    'Philidor Defense: Morphy Gambit',
    'Pirc Defense: Roscher Gambit',
    "King's Pawn Game: Gunderam Gambit",
    "Queen's Gambit Declined: Exchange Variation, Positional Variation #2",
    'Zukertort Opening: Wade Defense',
    'English Opening: Symmetrical Variation, Fianchetto Variation',
    'Hungarian Opening: Reversed Modern Defense',
    'Scandinavian Defense: Boehnke Gambit',
    'Gruenfeld Defense: Exchange Variation',
    'Yusupov-Rubinstein System',
    'Sicilian Defense: Canal-Sokolsky Attack',
    "Queen's Pawn Game: Colle System, Anti-Colle",
    "King's Gambit Accepted: King Knight's Gambit",
    'Vienna Game: Mengarini Variation',
    'Scotch Game: Scotch Gambit, Dubois Reti Defense',
    'Scotch Game: Goering Gambit',
    'Caro-Kann Defense: Panov Attack',
    "King's Indian Attack: Symmetrical Defense",
    'Caro-Kann Defense: Advance Variation, Bayonet Attack',
    'Czech Defense',
    'Sicilian Defense: Four Knights Variation',
    "Queen's Gambit Refused: Albin Countergambit, Normal Line",
    "Queen's Gambit Refused: Chigorin Defense, Exchange Variation",
    'Sicilian Defense: Modern Variations, Tartakower',
    "King's Gambit Declined, Classical Variation",
    'Sicilian Defense: Jalalabad Variation',
    'Indian Game: Omega Gambit',
    "King's Indian Defense: Four Pawns Attack",
    'Zukertort Opening: Ross Gambit',
    'Slav Defense: Slav Gambit, Alekhine Attack',
    'Sicilian Defense: Paulsen-Basman Defense',
    'Nimzowitsch-Larsen Attack',
    'Danish Gambit Accepted',
    'Gruenfeld Defense: Three Knights Variation, Burille Variation',
    'Scandinavian Defense: Blackburne-Kloosterboer Gambit',
    'Pirc Defense: Byrne Variation',
    'Ruy Lopez: Berlin Defense, Improved Steinitz Defense',
    'French Defense: Rubinstein Variation, Blackburne Defense',
    "King's Gambit, Falkbeer Countergambit, Blackburne Attack",
    'English Opening: Symmetrical Variation, Anti-Benoni Variation',
    "Queen's Pawn Game: Anglo-Slav Opening",
    "Queen's Gambit Refused: Baltic Defense, Pseudo-Slav",
    'Englund Gambit Declined, Reversed Krebs',
    'Sicilian Defense: Drazic Variation',
    'Dutch Defense: Raphael Variation',
    'Philidor Defense: Nimzowitsch Variation',
    'English Opening: Agincourt Defense #2',
    'Philidor Defense: Nimzowitsch Variation, Klein Variation',
    "Bishop's Opening: Vienna Hybrid",
    'French Defense: Perseus Gambit',
    'Portuguese Opening',
    "King's Indian Attack: French Variation",
    'Philidor Defense: Steinitz Variation',
    'Nimzowitsch Defense: Pseudo-Spanish Variation',
    'Center Game: von der Lasa Gambit',
    'Slav Defense: Quiet Variation',
    'French Defense: Winawer Variation, Advance Variation',
    'Italian Game: Two Knights Defense, Fritz Variation',
    'English Opening: Four Knights System, Nimzowitsch Variation',
    'Nimzowitsch Defense: Mikenas Variation',
    'Dutch Defense: Normal Variation',
    'Trompowsky Attack: Edge Variation',
    'Trompowsky Attack: Classical Defense',
    "King's Pawn Game: Beyer Gambit",
    'Sicilian Defense: Kan Variation',
    "King's Gambit Declined, Norwalde Variation",
    'Caro-Kann Defense: Tartakower Variation',
    'Blumenfeld Countergambit #2',
    'Petrov: Modern Attack',
    'Sicilian Defense: Wing Gambit',
    'Sicilian Defense: Nimzowitsch Variation, Closed Variation',
    'Ruy Lopez: Classical Variation, Central Variation',
    "King's Pawn Game: Tortoise Opening",
    'Budapest Defense',
    "Bishop's Opening: Ponziani Gambit",
    'Bird Opening: Williams Gambit',
    'Sicilian Defense: Lasker-Pelikan Variation',
    'Ruy Lopez: Exchange Variation, Normal Variation',
    'Benko Gambit',
    'Zukertort Opening: Arctic Defense',
    'Sicilian Defense: Kan Variation, Maroczy Bind, Reti Variation',
    'Ruy Lopez: Exchange Variation, Keres Variation',
    'Budapest Defense: Rubinstein Variation',
    'French Defense',
    "Queen's Gambit Declined: Traditional Variation",
    "King's Gambit Accepted, Modern Defense",
    'French Defense: Advance Variation, Main Line',
    "Benoni Defense: King's Pawn Line",
    'Catalan Opening: Closed Variation',
    'Vienna Game: Stanley Variation, Three Knights Variation',
    'Colle System: Traditional Colle',
    'Ruy Lopez: Berlin Defense',
    'Italian Game: Classical Variation, Greco Gambit, Traditional Line',
    'Philidor Defense: Lopez Countergambit',
    'Nimzowitsch Defense: Kennedy Variation',
    'Ruy Lopez: Berlin Defense, Rio Gambit Accepted',
    'Nimzowitsch Defense: Scandinavian Variation, Bogoljubov Variation, Vehre Variation',
    'French Defense: Burn Variation',
    'Sicilian Defense: Kan Variation, Modern Variation',
    'Sicilian Defense: Closed #2',
    'Sicilian Defense: Alapin Variation, Barmen Defense',
    "Queen's Gambit Accepted: Central Variation, Modern Defense",
    "Queen's Gambit Refused: Chigorin Defense, Janowski Variation",
    'Scotch Game: Scotch Gambit, Advance Variation',
    'Grob Opening: Grob Gambit',
    'Vienna Game #2',
    'Modern Defense: Mongredien Defense',
    "King's Pawn Game: Dresden Opening",
    "Queen's Gambit Declined: Exchange Variation, Positional Variation",
    "Ruy Lopez: Exchange Variation, King's Bishop Variation",
    'Sicilian Defense: Closed Variation, Fianchetto Variation',
    'Sicilian Defense: Mengarini Variation',
    'Scotch Game: Relfsson Gambit',
    'Ruy Lopez: Morphy Defense, Neo-Arkhangelsk Variation',
    'Scotch Game: Mieses Variation',
    'Indian Game: Przepiorka Variation',
    'Sicilian Defense: Lasker-Pelikan Variation, Sveshnikov Variation, Chelyabinsk Variation',
    'Sicilian Defense: Dragon Variation, Yugoslav Attack, Modern Line',
    'Vienna Game: Omaha Gambit',
    'Four Knights Game: Halloween Gambit',
    'Nimzowitsch Defense: Lean Variation, Colorado Counter Accepted',
    'Russian Game: Classical Attack',
    'Sicilian Defense: Kalashnikov Variation',
    'Alekhine Defense: Balogh Variation',
    "Sicilian Defense: O'Kelly Variation, Yerevan System",
    'Caro-Kann Defense: Advance Variation, Tal Variation',
    "King's Gambit Accepted, Bonsch-Osmolovsky Variation",
    "Queen's Gambit Refused: Chigorin Defense #3",
    "Queen's Pawn Opening: Veresov, Richter Attack",
    'Blackmar-Diemer Gambit: Zeller Defense',
    'Center Game: Hall Variation',
    'Scandinavian Defense: Portuguese Variation',
    'Zukertort Opening: Dutch Variation',
    'Modern Defense: Two Knights Variation, Suttles Variation',
    'Grob Opening: Grob Gambit, Fritz Gambit',
    'Alekhine Defense: Two Pawn Attack, Lasker Variation',
    'French Defense: Advance, Steinitz Variation',
    "English Opening: King's English Variation, Nimzowitsch Variation",
    'French Defense: Reti-Spielmann Attack',
    'Kangaroo Defense',
    'Philidor Defense: Nimzowitsch Variation #2',
    'Blackmar-Diemer Gambit: Gedult Gambit',
    "Lion Defense: Lion's Jaw",
    "Queen's Gambit Accepted: Central Variation, McDonnell Defense",
    "King's Indian Defense: Normal Variation",
    'Borg Defense: Borg Gambit',
    "King's Gambit, Falkbeer Countergambit, Staunton Line",
    'Amar Opening',
    'Sicilian Defense: Godiva Variation',
    'Caro-Kann Defense: Advance Variation, Van der Wiel Attack',
    'English Opening: Anglo-Lithuanian Variation',
    'Sicilian Defense: Smith-Morra Gambit Deferred',
    'Four Knights Game: Double Spanish',
    "English Opening: Anglo-Indian Defense, King's Indian Formation",
    'Canard Opening',
    "King's Gambit Declined, Petrov's Defense",
    'Sicilian Defense: Sozin, not Scheveningen',
    "King's Pawn Game: Mengarini's Opening",
    'Sicilian Defense: Paulsen Variation, Bastrikov Variation',
    "English Opening: King's English Variation, Four Knights Variation, Fianchetto Line",
    'Russian Game: Nimzowitsch Attack',
    "English Opening: King's English Variation, Kramnik-Shirov Counterattack",
    'Ruy Lopez: Morphy Defense, Steinitz Deferred',
    'Sicilian Defense: Hyperaccelerated Pterodactyl',
    'Kangaroo Defense: Keres Defense, Transpositional Variation',
    "Queen's Gambit Declined: Tarrasch Defense, Pseudo-Tarrasch",
    'Gruenfeld Defense: Three Knights Variation, Petrosian System',
    'English Opening: Anglo-Gruenfeld Defense',
    'St. George Defense: Polish Variation',
    'Three Knights Opening: Winawer Defense',
    "King's Indian Defense: Fianchetto Variation, Yugoslav Variation",
    "King's Knight Opening: Konstantinopolsky",
    "Queen's Gambit Declined: Barmen Variation",
    "King's Gambit Declined: Falkbeer Countergambit",
    'Italian Game: Two Knights Defense, Traxler Counterattack, Knight Sacrifice Line',
    "King's Gambit Declined: Keene's Defense #2",
    'Alekhine Defense: Modern Variation, Main Line',
    'Blackmar-Diemer Gambit: Ryder Gambit',
    'Ruy Lopez: Morphy Defense',
    'French Defense: Chigorin Variation',
    'French Defense: Tarrasch Variation, Open System, Suechting Line',
    'Philidor Defense: Philidor Countergambit, Zukertort Variation',
    'Semi-Slav Defense: Bogoljubov Variation',
    "Bishop's Opening: Vienna Hybrid, Spielmann Attack",
    'Sicilian Defense: Scheveningen Variation, Classical Variation',
    'Scotch Game: Lolli Variation',
    'Sicilian Defense: Najdorf Variation, Zagreb (Fianchetto) Variation',
    "Queen's Gambit Declined: Semi-Tarrasch Defense, Pillsbury Variation",
    'Danish Gambit Declined, Sorensen Defense',
    'Sicilian Defense: Accelerated Dragon, Exchange Variation',
    'Scotch Game: Potter Variation',
    'Slav Indian',
    'Sicilian Defense: Keres Variation',
    'Italian Game: Two Knights Defense, Polerio Defense, Suhle Defense',
    'Caro-Kann Defense: Bronstein-Larsen Variation',
    'Slav Defense: Geller Gambit #2',
    'Semi-Slav Defense: Marshall Gambit',
    "King's Indian Defense: Semi-Classical Variation",
    'Old Indian Defense: Ukrainian Variation',
    "Queen's Gambit Declined: 4.Bg5 Be7, 5.e3 O-O",
    'Four Knights Game: Ranken Variation',
    'Dutch Defense: Classical Variation, Stonewall Variation',
    'Lemming Defense',
    'Grob Opening: Grob Gambit Declined',
    'Ruy Lopez: Nuernberg Variation',
    'Russian Game: Cochrane Gambit',
    'Center Game: Kieseritzky Variation #2',
    'Dutch Defense: Hopton Attack',
    'Scandinavian Defense: Modern Variation',
    "King's Gambit, Falkbeer Countergambit Accepted",
    "Queen's Gambit Accepted: Showalter Variation",
    'Ruy Lopez: Schliemann Defense',
    "King's Indian Defense: Smyslov Variation",
    'English Opening: Anglo-Scandinavian Defense, Malvinas Variation',
    'French Defense: Schlechter Variation',
    "Queen's Pawn Game: Liedmann Gambit",
    "English Opening: King's English Variation, Four Knights Variation, Quiet Line #3",
    'Alekhine Defense: Krejcik Variation',
    'Grob Opening: Spike, Hurst Attack',
    'Alekhine Defense: Scandinavian Variation, Geschev Gambit',
    'Van Geet Opening: Dunst-Perrenet Gambit',
    'Sicilian Defense: Smith-Morra Gambit Declined, Push Variation',
    'Lasker Simul Special',
    "King's Gambit Accepted, Polerio Gambit",
    'Nimzo-Indian Defense: Classical Variation',
    "King's Indian Attack: Keres Variation #2",
    'Nimzowitsch Defense: Kennedy Variation, Paulsen Attack',
    'Italian Game: Scotch Gambit Declined',
    'Benoni Defense: Weenink Variation',
    'Blackmar-Diemer Gambit: Teichmann Variation',
    'Nimzo-Indian Defense: Classical Variation, Berlin Variation',
    'Scandinavian Defense: Modern Variation, Gipslis Variation',
    'French Defense: Steinitz Variation #2',
    "English Opening: King's English Variation, Two Knights Variation, Keres Variation",
    'Slav Defense: Quiet Variation, Schallopp Defense',
    'English Opening: Anglo-Indian Defense, Old Indian Formation',
    'Philidor Defense: Philidor Countergambit',
    'Nimzowitsch Defense: Kennedy Variation, de Smet Gambit',
    'Caro-Kann Defense: Accelerated Panov Attack',
    "Polish Opening: King's Indian Variation",
    'Scotch Game: Scotch Gambit, London Defense',
    'Sicilian Defense: Sozin Attack',
    'Sicilian Defense: Wing Gambit, Carlsbad Variation',
    'Latvian Gambit: Mlotkowski Variation',
    "Queen's Gambit Declined: Charousek (Petrosian) Variation",
    'English Opening: Agincourt Defense, Catalan Defense Accepted',
    'Gruenfeld Defense: Three Knights Variation',
    "King's Gambit Accepted",
    'Slav Defense: Schlechter Variation',
    'Scandinavian Defense: Kloosterboer Gambit',
    'Trompowsky Attack: Classical Defense, Big Center Variation',
    'Sicilian Defense: Kan Variation, Wing Attack',
    'Englund Gambit Complex: Felbecker Gambit',
    'French Defense: Winawer Variation',
    'Italian Game: Two Knights Defense, Polerio Defense, Bogoljubov Variation',
    'Englund Gambit Declined, Reversed Alekhine',
    "King's Gambit Accepted, Bishop's Gambit",
    'Three Knights Opening: Steinitz Defense',
    'French Defense: Wing Gambit',
    'Indian Game: Anti-Gruenfeld, Advance Variation',
    'Philidor Defense: Bird Gambit',
    'Sicilian Defense: Myers Attack #2',
    'Slav Defense: Chameleon Variation',
    'Ruy Lopez: Closed Variations, Center Attack',
    'Benoni Defense: Czech Benoni Defense',
    'French Defense: Pelikan Variation',
    'Sicilian Defense: Sozin Attack, Leonhardt Variation',
    'Semi-Slav Defense: Normal Variation',
    'Ruy Lopez: Morphy Defense, Tarrasch Variation',
    'Budapest Defense: Alekhine Variation',
    'Sicilian Defense: Morphy Gambit, Andreaschek Gambit',
    'English Opening: Agincourt Defense, Catalan Defense, Semi-Slav Defense',
    "Queen's Pawn Game: Veresov Attack, Veresov Variation",
    'Nimzowitsch Defense: Scandinavian Variation, Bogoljubov Variation',
    'English Opening: Symmetrical Variation, Anti-Benoni Variation, Spielmann Defense',
    'English Opening: Anglo-Scandinavian Defense, Schulz Gambit',
    "King's Pawn Game: Alapin Opening",
    'Sicilian Defense: Dragon, Classical Attack',
    'French Defense: Winawer Variation, Delayed Exchange Variation',
    'Sicilian Defense: Najdorf Variation, Adams Attack',
    'Sodium Attack',
    "Bishop's Opening: Philidor Variation",
    'English Opening: Anglo-Indian Defense, Scandinavian Defense',
    "King's Gambit Accepted, Abbazia Defense",
    'Caro-Kann Defense: Rasa-Studier Gambit',
    'Creepy Crawly Formation: Classical Defense',
    'Sicilian Defense: Alapin Variation, Smith-Morra Declined',
    "King's Indian Defense: Orthodox Variation, Classical System",
    'Italian Game: Giuoco Pianissimo, Canal Variation',
    'Modern Defense: Bishop Attack',
    'English Opening: Agincourt Defense, Neo-Catalan Declined',
    "Queen's Gambit Declined: Tarrasch Defense: 4.cxd5 exd5",
    'Slav Defense: Bonet Gambit',
    'English Opening: Agincourt Defense #3',
    'French Defense: Exchange Variation, Svenonius Variation',
    'French Defense: Steinitz Variation, Boleslavsky Variation',
    "Indian Game: Colle System, King's Indian Variation",
    'Polish Opening: Symmetrical Variation',
    'Sicilian Defense: Prins Variation',
    "King's Indian Attack: Sicilian Variation",
    'Sicilian Defense: Smith-Morra Gambit Accepted, Paulsen Formation',
    'Ruy Lopez: Morphy Defense, Modern Steinitz Defense',
    'English Opening: Symmetrical Variation, Four Knights Variation',
    'Italian Game: Two Knights Defense, Polerio Defense',
    'Sicilian Defense: Halasz Gambit',
    'French Defense: Tarrasch Variation, Closed Variation #2',
    'Pirc Defense: Austrian Attack, Weiss Variation',
    'Ruy Lopez: Fianchetto Defense',
    "Queen's Gambit Declined: Vienna Variation, Quiet Variation",
    'Zukertort Opening: Polish Defense',
    "King's Indian Defense: Makogonov Variation",
    "Queen's Indian Defense",
    "King's Indian Defense: Accelerated Averbakh Variation",
    "King's Pawn Game: Clam Variation, King's Gambit Reversed",
    'Caro-Kann Defense: Classical, Spassky Variation',
    'Italian Game: Two Knights Defense, Traxler Counterattack, Bishop Sacrifice Line',
    'Blackmar-Diemer Gambit: von Popiel Gambit',
    'Italian Game: Two Knights Defense, Open Variation',
    'Pterodactyl Defense: Eastern, Benoni',
    "Queen's Gambit Declined: Exchange Variation, Reshevsky Variation",
    "Queen's Gambit Declined: Ragozin Defense, Vienna Variation",
    'Gruenfeld Defense: Stockholm Variation',
    'Blackmar-Diemer Gambit Declined, Weinsbach Declination',
    'Sicilian Defense: Dragon Variation, Yugoslav Attack',
    'Sicilian Defense: Pin Variation',
    'Blackmar-Diemer Gambit: Vienna Variation',
    "King's Gambit Declined, Miles Defense",
    'Pirc Defense: Classical Variation #2',
    'Philidor Defense: Larsen Variation',
    'Alekhine Defense: Saemisch Attack',
    'Mexican Defense',
    'Sicilian Defense: Dragon Variation, Levenfish Variation',
    "King's Pawn Game: King's Head Opening",
    'Ruy Lopez: Closed Variations, Martinez Variation',
    'Scandinavian Defense: Main Line, Leonhardt Gambit',
    "Queen's Gambit Refused: Austrian Attack, Salvio Countergambit",
    'Alekhine Defense: Brooklyn Variation',
    'Italian Game: Two Knights Defense, Ulvestad Variation',
    'Sicilian Defense: French Variation, Westerinen Attack',
    'Alekhine Defense: Mokele Mbembe',
    'Russian Game: French Attack',
    'Sicilian Defense: Nimzowitsch Variation, Advance Variation',
    "Indian Game: King's Indian Variation, Fianchetto Variation",
    'Sicilian Defense: Four Knights Variation, Exchange Variation',
    'Ruy Lopez: Morphy Defense, Modern Steinitz Defense #2',
    'Semi-Slav Defense: Chigorin Defense',
    'Wade Defense',
    "Queen's Gambit Declined: Semi-Tarrasch, 5.cxd5",
    'Nimzo-Indian Defense: Three Knights Variation, Duchamp Variation',
    'Zukertort Opening: Quiet System',
    'Mikenas Defense: Lithuanian Variation',
    'Semi-Slav Defense: Noteboom Variation',
    'Italian Game: Evans Gambit, McDonnell Defense',
    'Benko Gambit Accepted, Modern Variation',
    'Caro-Kann Defense: Two Knights Attack, Mindeno Variation',
    'French Defense: Tarrasch Variation, Pawn Center Variation',
    'Center Game: Kieseritzky Variation #4',
    'Nimzo-Indian Defense: Saemisch Variation, Accelerated',
    "Queen's Pawn Game: Huebsch Gambit",
    "Queen's Pawn Opening: Veresov Attack, Irish Gambit",
    'Sicilian Defense: Lasker-Pelikan Variation, Exchange Variation',
    'Ruy Lopez: Morphy Defense, Classical Defense Deferred',
    "English Opening: Anglo-Indian Defense, King's Knight Variation",
    'Caro-Kann Defense: Masi Variation',
    'Italian Game: Evans Gambit',
    'French Defense: Tarrasch, Open, 4.exd5 exd5',
    'Neo-Gruenfeld Defense: Ultra-delayed Exchange Variation',
    'Guatemala Defense',
    "Queen's Indian Defense: Spassky System",
    "Queen's Gambit Accepted: Normal Variation, Traditional System",
    "King's Indian Defense: Saemisch Variation, Normal Defense",
    "English Opening: King's English Variation, Four Knights Variation, Flexible Line",
    "King's Gambit: Panteldakis Countergambit",
    'Sicilian Defense: Lasker-Pelikan Variation, Retreat Variation',
    'Zukertort Opening: Vos Gambit',
    "King's Indian Defense: 3.Nc3",
    "Queen's Gambit Accepted: Deferred Variation",
    'Caro-Kann Defense: Accelerated Panov Attack, Open Variation',
    'Modern Defense: Pseudo-Austrian Attack',
    'Modern Defense: Averbakh System, Kotov Variation',
    'Ruy Lopez: Spanish Countergambit',
    'Italian Game: Deutz Gambit',
    "Sicilian Defense: O'Kelly Variation, Normal System, Taimanov Line",
    'Caro-Kann Defense: Classical Variation, Main Line',
    'Scotch Game: Malaniuk Variation',
    "King's Indian Defense: Orthodox Variation, Positional Defense, Closed Line",
    'Nimzowitsch Defense: Lean Variation',
    'Dutch Defense: Fianchetto Attack',
    'Polish Opening: Bugayev Attack',
    'Caro-Kann Defense: Accelerated Panov Attack, Modern Variation',
    "Queen's Indian Accelerated",
    'Ponziani Opening: Ponziani Countergambit',
    'Sicilian Defense: Lasker-Pelikan Variation, Schlechter Variation',
    'English Opening: Symmetrical Variation, Symmetrical Variation',
    'Semi-Slav Defense: Accelerated Meran Variation',
    'Nimzo-Indian Defense: Saemisch Variation',
    'Zukertort Opening',
    'Sicilian Defense: Smith-Morra Gambit Accepted, Scheveningen Formation',
    "Queen's Gambit Refused: Chigorin Defense, Main Line",
    'Caro-Kann Defense: Karpov Variation',
    'Modern Defense: Norwegian Defense',
    'Italian Game: Two Knights Defense, Ponziani-Steinitz Gambit',
    'Blackmar-Diemer Gambit: Netherlands Variation',
    'Alekhine Defense: Four Pawns Attack',
    'Scotch Game: Steinitz Variation',
    'Sicilian Defense: Closed Variation, Chameleon Variation',
    'Modern Defense: Beefeater Variation',
    "King's Gambit Declined, Keene Defense",
    'Caro-Kann Defense: Euwe Attack',
    'Rat Defense: Balogh Defense',
    "Italian Game: Giuoco Piano, Greco's Attack",
    'Four Knights Game: Spanish Variation, Rubinstein Variation',
    'Caro-Kann Defense: Classical Variation, Flohr Variation',
    'Blackmar-Diemer Gambit: Fritz Attack',
    'Alekhine Defense: Modern Variation, Alburt Variation',
    'Sicilian Defense: Scheveningen Variation',
    'Caro-Kann Defense: Panov Attack, Modern Defense, Mieses Line',
    'Polish Opening: Outflank Variation',
    'Zukertort Opening: St. George Defense',
    "Queen's Gambit Declined: Orthodox Defense",
    "English Opening: King's English Variation, Three Knights System",
    'Sicilian Defense: Quinteros Variation',
    'French Defense: Carlson Gambit',
    'Indian Game: Normal Variation',
    'Blackmar-Diemer Gambit #2',
    "Queen's Gambit Declined: Slav, Dutch Variation",
    'Philidor Defense: Boden Variation',
    'Danish Gambit Accepted, Classical Defense',
    'French Defense: Advance Variation, Ruisdonk Gambit',
    'Blackmar-Diemer Gambit Declined, Langeheinecke Defense',
    'Gruenfeld Defense: Three Knights Variation, Paris Variation',
    'Pirc Defense: Classical Variation, Quiet System',
    'Sicilian Defense: Scheveningen Variation, Keres Attack',
    'Sicilian Defense: Dragon Variation, Yugoslav Attack, Main Line',
    'French Defense: Tarrasch Variation, Open System, Euwe-Keres Line',
    "Bishop's Opening: Calabrese Countergambit",
    'French Defense: Classical Variation, Swiss Variation',
    'Sicilian Defense: Sozin Attack, Flank Variation',
    'Italian Game: Classical Variation, Greco Gambit',
    'Center Game: Kieseritzky Variation #3',
    'Indian Game: Czech-Indian',
    'Scandinavian Defense: Anderssen Counterattack, Collijn Variation',
    "King's Gambit Accepted, Kieseritzky Gambit, Kolisch Defense",
    'French Defense: Tarrasch Variation, Open System',
    'Slav Defense: Winawer Countergambit',
    'Bird Opening: Schlechter Gambit',
    'Sicilian Defense: Smith-Morra Gambit Declined, Scandinavian Formation',
    "King's Gambit Accepted, Cunningham Defense, McCormick Defense",
    'Gruenfeld Defense: Exchange Variation, Classical Variation',
    'Sicilian Defense: French Variation, Normal',
    'Hippopotamus Defense #2',
    "Queen's Gambit Accepted: Gunsberg Defense",
    'Gruenfeld Defense: Exchange Variation, Modern Exchange Variation',
    "King's Gambit Accepted, Bishop's Gambit, Cozio Defense",
    'Sicilian Defense: Accelerated Dragon, Maroczy Bind',
    'Alekhine Defense: Modern Variation',
    'Nimzowitsch Defense: Kennedy Variation, Main Line',
    'Italian Game: Two Knights Defense, Max Lange Attack',
    'Italian Game: Two Knights Defense, Perreux Variation',
    'Benoni Defense: Classical Variation',
    'Scandinavian Defense: Bronstein Variation',
    'Indian Game: Reversed Chigorin Defense',
    'Nimzowitsch Defense: Kennedy Variation, Riemann Defense',
    "King's Indian Defense: Larsen Variation",
    'Sicilian Defense: Wing Gambit, Marshall Variation',
    'Slav Defense: Geller Gambit',
    "Benoni Defense: Knight's Tour Variation",
    'Sicilian Defense: Scheveningen Variation, English Attack',
    'English Opening: Anglo-Scandinavian Defense, Loehn Gambit',
    "King's Indian Attack: Wahls Defense",
    "Queen's Gambit Refused: Chigorin Defense, Modern Gambit",
    "English Opening: King's English Variation, Taimanov Variation",
    'Nimzo-Indian Defense: Normal Line',
    'Alekhine Defense: Modern Variation, Alekhine Variation',
    'French Defense: Classical Variation, Alapin Variation',
    'Slav Defense: Two Knights Attack',
    'Philidor Defense: Paulsen Attack',
    "King's Gambit Accepted, Bishop's Gambit, Maurian Defense",
    "Queen's Indian Defense: Capablanca Variation",
    'Slav Defense: Alekhine Variation',
    "King's Indian Defense: Orthodox Variation, Positional Defense",
    "Queen's Gambit Accepted: Classical Defense, Rubinstein Variation",
    'Russian Game: Damiano Variation, Kholmov Gambit',
    'French Defense: Diemer-Duhm Gambit',
    'Scotch Game: Modern Defense',
    "Queen's Gambit Declined: Harrwitz Attack, Fianchetto Defense",
    "King's Indian Defense: Fianchetto Variation, Uhlmann-Szabo System",
    'Sicilian Defense: Najdorf Variation, Amsterdam Variation',
    "King's Indian Defense: Saemisch Variation, Orthodox Variation",
    "Queen's Gambit Declined: Neo-Orthodox Variation, Main Line",
    "Queen's Gambit Declined: Orthodox Defense, Botvinnik Variation",
    "Sicilian Defense: O'Kelly Variation, Venice System",
    'English Opening: Anglo-Indian Defense, Scandinavian Defense, Exchange Variation',
    "Bishop's Opening: Urusov Gambit, Keidansky Gambit",
    'Indian Game: Paleface Attack, Blackmar-Diemer Gambit Deferred',
    'Australian Defense',
    'Sicilian Defense: Nimzowitsch Variation',
    'Hungarian Opening: Reversed Alekhine',
    'French Defense: Winawer Variation, Fingerslip Variation',
    'Ruy Lopez: Exchange Variation, Gligoric Variation',
    'Caro-Kann Defense: Panov Attack, Modern Defense',
    'Zukertort Opening: Speelsmet Gambit',
    'Vienna Game: Paulsen Variation',
    'Old Indian Defense: Two Knights Variation',
    'French Defense: Winawer Variation, Classical Variation',
    'English Opening: Symmetrical Variation, Full Symmetry Line',
    'Vienna Game: Vienna Gambit, Steinitz Gambit, Knight Variation',
    'Old Indian: Czech Variation, with Nc3',
    'Scandinavian Defense: Lasker Variation',
    'Neo-Gruenfeld Defense: Classical Variation, Original Defense',
    'Caro-Kann Defense: von Hennig Gambit',
    'Italian Game: Two Knights Defense #2',
    'French Defense: Classical Variation, Delayed Exchange Variation',
    'Ruy Lopez: Morphy Defense #2',
    'Gruenfeld Defense',
    'French Defense: Classical Variation',
    'English Opening: Symmetrical Variation, Botvinnik System',
    'Sicilian Defense: Closed Variation, Korchnoi Defense',
    "Queen's Pawn Game: Colle System, Gruenfeld Formation",
    'Russian Game: Paulsen Attack',
    'Sicilian Defense: Modern Variations, Anti-Qxd4 Move Order',
    'Italian Game: Scotch Gambit, Max Lange Attack, Spielmann Defense',
    'Gruenfeld Defense: Exchange Variation, Spassky Variation',
    "Queen's Gambit Declined: Modern, Knight Defense",
    'Zukertort Opening: Gruenfeld Reversed',
    'Catalan Opening',
    'English Opening: Anglo-Indian Defense, Anglo-Gruenfeld Variation #3',
    'Caro-Kann Defense: Modern Variation',
    'Ruy Lopez: Closed Variations, Chigorin Defense',
    'Montevideo Defense',
    'Nimzo-Indian Defense: Panov Attack, Main Line',
    'Semi-Bononi',
    'Ruy Lopez: Marshall Attack',
    'Benoni Defense: Taimanov Variation',
    'Ruy Lopez: Berlin Defense, Closed Wolf Variation',
    'Caro-Kann Defense: Goldman Variation',
    'Englund Gambit Complex: Zilbermints Gambit',
    'Nimzowitsch Defense: Breyer Variation',
    "King's Indian Attack: Yugoslav Variation",
    'Latvian Gambit: Mason Countergambit',
    "Petrov's Defense #5",
    'Pterodactyl Defense: Western, Rhamphorhynchus',
    'Sicilian Defense: Dragon Variation, Fianchetto Variation',
    "King's Indian Defense: Fianchetto Variation, Debrecen Defense",
    "Queen's Gambit Declined: Cambridge Springs Variation",
    'Scotch Game: Scotch Gambit, Sarratt Variation',
    "King's Indian Defense: Orthodox Variation, Bayonet Attack",
    "English Opening: King's English Variation, Nimzowitsch-Flohr Variation",
    'French Defense: Tarrasch Variation, Closed Variation, Main Line',
    'Italian Game: Classical Variation, La Bourdonnais Variation',
    'Scotch Game #3',
    'Semi-Slav Defense: Anti-Moscow Gambit',
    "King's Gambit Accepted, Breyer Gambit",
    'Caro-Kann Defense: De Bruycker Defense',
    'Benoni Defense: Old Benoni, Schmid Variation',
    "Queen's Gambit Refused: Albin Countergambit, Tartakower Defense",
    'Slav Defense: Diemer Gambit',
    'Torre Attack: Wagner Gambit',
    'Benko Gambit Declined, Main Line',
    "King's Gambit, Falkbeer Countergambit, Charousek Gambit",
    'Sicilian Defense: Mongoose Variation',
    'Latvian Gambit Accepted, Bilguer Variation',
    'Dutch Defense: Staunton Gambit',
    "King's Indian Defense: Kramer Variation",
    'Nimzowitsch Defense: Scandinavian Variation, Exchange Variation, Marshall Gambit',
    'Italian Game: Evans Gambit, Harding Variation',
    "Queen's Gambit Accepted: Central Variation, Rubinstein Defense",
    'St. George Defense: New St. George, Three Pawn Attack',
    'Benko Gambit Accepted, Fully Accepted Variation',
    'Sicilian Defense: Dragon, Classical, Amsterdam Variation',
    "Italian Game: Bird's Attack",
    'Ruy Lopez: Open Variations',
    "King's Gambit Accepted, Gianutio Countergambit",
    "King's Indian Defense: Saemisch Variation, Closed Variation, 7...c6",
    'Russian Game: Classical Attack, Closed Variation',
    'Pirc Defense: Austrian Attack, Ljubojevic Variation',
    "Queen's Indian Defense: Kasparov Variation",
    'Alekhine Defense: Four Pawns Attack, 6...Nc6',
    'Blumenfeld Countergambit',
    "King's Indian Defense: Petrosian Variation, Stein Defense",
    'Van Geet Opening: Gruenfeld Defense, Steiner Gambit',
    'Sicilian Defense: Venice Attack',
    'Zukertort Opening: Nimzo-Larsen Variation',
    "Queen's Pawn Game: Veresov Attack, Dutch System",
    'Catalan Opening: Open Defense',
    'Bogo-Indian Defense: Exchange Variation',
    "Ruy Lopez: Open Berlin Defense: l'Hermet Variation",
    "King's Gambit Declined, Mafia Defense",
    'Van Geet Opening: Gruenfeld Defense',
    'Scandinavian Defense: Kiel Variation',
    "King's Pawn Game: Macleod Attack, Lasa Gambit",
    'Sicilian Defense: Myers Attack',
    'French Defense: Alekhine-Chatard Attack, Breyer Variation',
    'French Defense: Classical Variation, Pollock Variation',
    'Polish Opening: Baltic Defense',
    "Queen's Gambit Declined: Capablanca",
    "King's Gambit Declined, Classical Variation #2",
    'Global Opening',
    'Dutch Defense: Stonewall Variation, Modern Variation',
    'Sicilian Defense: Boleslavsky Variation',
    'Scotch Game: Ghulam-Kassim Variation',
    'Ruy Lopez: Closed Variations, Smyslov Defense',
    'Vienna Game: Mieses Variation',
    'English Opening: Mikenas-Carls Variation #2',
    "King's Indian Defense: Four Pawns Attack, Dynamic Attack",
    'Sicilian Defense: Kronberger Variation',
    'Danish Gambit Accepted, Schlechter Defense',
    'Alekhine Defense: Four Pawns Attack, Trifunovic Variation',
    'Italian Game: Scotch Gambit, Janowski Defense',
    'Italian Game: Two Knights Defense, Polerio Defense, Kieseritzky Variation',
    'Italian Game: Classical Variation, Greco Gambit, Moeller-Therkatz Attack',
    'Elephant Gambit: Maroczy Gambit',
    'Alekhine Defense: Modern Variation, Larsen Variation',
    'Italian Game: Evans Gambit Declined',
    'Blackmar-Diemer Gambit: Ziegler Defense',
    'Modern Defense: Lizard Defense, Mittenberger Gambit',
    "English Opening: King's English Variation, Keres Defense",
    "Queen's Pawn Game: Veresov Attack, Shaviliuk Gambit",
    'Zukertort Opening: Ware Defense',
    "King's Indian, Fianchetto, Classical Variation, 8.e4",
    "Queen's Gambit Declined: Harrwitz Attack, Orthodox Defense",
    'French Defense: Steinitz Variation, Gledhill Attack',
    'Sicilian Defense: Accelerated Fianchetto, Maroczy Bind, 5...Bg7',
    "King's Indian Defense: Fianchetto Variation, Classical Fianchetto",
    "King's Gambit Accepted, Rosentreter Gambit, Bird Gambit",
    "King's Gambit, Falkbeer Countergambit, Nimzowitsch-Marshall Countergambit",
    'Semi-Slav Defense: Noteboom Variation, Anti-Noteboom Gambit',
    "King's Indian Defense: Steiner Attack",
    'Sicilian Defense: Dragon Variation, Yugoslav Attack, Panov Variation',
    'Sicilian Defense: Scheveningen Variation, Modern Variation #3',
    'Alekhine Defense: Hunt Variation, Lasker Simul Gambit',
    'French Defense: La Bourdonnais Variation, Reuter Gambit',
    "Sicilian Defense: O'Kelly Variation, Kieseritzky System",
    "Bishop's Opening: Stein Gambit",
    "King's Gambit, Falkbeer Countergambit, Hinrichsen Gambit",
    'Nimzo-Indian Defense: Classical Variation, Noa Variation',
    "King's Gambit Accepted, Traditional Variation",
    'Vienna Game: Vienna Gambit, Steinitz Gambit',
    'French Defense: Classical Variation, Tartakower Variation',
    'Ruy Lopez: Classical Variation, Cordel Gambit',
    'Pterodactyl Defense: Queen Pterodactyl, Quiet Line',
    'Danish Gambit Accepted, Chigorin Defense',
    'French Defense: Tarrasch Variation, Open System, Main Line',
    "King's Gambit Accepted: Bishop's Gambit, Steinitz Defense",
    "King's Gambit Accepted, Salvio Gambit",
    'Nimzo-Indian Defense: Normal Variation, Ragozin Variation',
    "King's Indian Defense: Fianchetto Variation, Panno Variation",
    'Sicilian Defense: Scheveningen Variation, Modern Variation',
    'French Defense: Winawer Variation, Advance Variation #3',
    'Caro-Kann Defense: Gurgenidze Counterattack',
    'Rubinstein Opening',
    'Budapest Defense: Fajarowicz Variation',
    'Benoni Defense: Benoni-Indian Defense',
    'Alekhine Defense: Four Pawns Attack, Main Line',
    'Semi-Slav Defense: Meran Variation',
    "Queen's Gambit Accepted: Janowski-Larsen Variation",
    "English Opening: King's English Variation, Two Knights Variation, Reversed Dragon",
    'English Orangutan',
    'Englund Gambit Complex: Soller Gambit Deferred',
    'Benoni Defense: Classical Variation, Czerniak Defense, Tal Line',
    'Alekhine Defense: The Squirrel',
    'Four Knights Game: Italian Variation, Noa Gambit',
    'Benoni Defense: Benoni-Indian Defense, Kingside Move Order',
    'French Defense: Alekhine-Chatard Attack, Maroczy Variation',
    'Benko Gambit Accepted, Pawn Return Variation',
    "Queen's Indian Defense: Fianchetto Variation, Nimzowitsch Variation",
    'Ruy Lopez: Rotary-Albany Gambit',
    'Pirc Defense: Classical Variation, Schlechter Variation',
    "Queen's Gambit Declined: Orthodox Defense, Rubinstein Variation",
    'Reti Opening: Anglo-Slav Variation, Bogoljubov Variation, Stonewall Line',
    'Benko Gambit: Zaitsev System',
    'Sicilian Defense: Buecker Variation',
    'Neo-Gruenfeld Defense: Classical Variation, Modern Defense',
    'Sicilian Defense: Pin Variation, Koch Variation',
    'Semi-Slav Defense: Quiet Variation',
    'French Defense: Advance Variation, Wade Variation',
    'Italian Game: Classical Variation',
    'French Defense: Alapin Gambit',
    'Italian Game: Classical Variation, Center Attack',
    "Queen's Gambit Declined: Harrwitz Attack, Two Knights Defense",
    "Queen's Gambit Declined: Semi-Tarrasch Defense",
    'Gruenfeld Defense: Lutikov Variation',
    'Sicilian Defense: Dragon, 6.Be3',
    'Van Geet Opening: Napoleon Attack',
    'Ruy Lopez: Closed Variations, Flohr System',
    'Philidor Defense: Philidor Gambit',
    'Nimzo-Indian Defense: Huebner Variation, Rubinstein Variation',
    'Ruy Lopez: Morphy Defense, Wormald Attack',
    "King's Indian Defense: Kazakh Variation",
    'Zukertort Opening: Lisitsyn Gambit',
    'Gruenfeld Defense: Exchange Variation, Sokolsky Variation',
    'Caro-Kann Defense: Advance Variation, Bronstein Variation',
    'Bogo-Indian Defense: Retreat Variation',
    "Bishop's Opening: Calabrese Countergambit, Jaenisch Variation",
    'English Opening: Neo-Catalan',
    "King's Indian Defense: Petrosian Variation, Normal Defense",
    'Blackmar-Diemer Gambit: Euwe Defense',
    'Ruy Lopez: Closed',
    "Bishop's Opening: Urusov Gambit",
    "Bishop's Opening: Anderssen Gambit",
    "King's Indian Defense: Saemisch Variation",
    "Bishop's Opening: Khan Gambit",
    "King's Gambit Accepted, Rosentreter Gambit",
    'Semi-Slav Defense: Stoltz Variation',
    "King's Indian Defense: Exchange Variation",
    "King's Gambit Declined: Classical, Soldatenkov Variation",
    'Bird Opening: Wagner-Zwitersch Gambit',
    "King's Gambit Accepted, Blachly Gambit",
    'Pterodactyl Defense: Eastern, Anhanguera',
    'Ruy Lopez: Berlin Defense, Anderssen Variation',
    'Russian Game: Modern Attack, Center Variation',
    'French Defense: Franco-Hiva Gambit I',
    "King's Gambit Accepted, Hanstein Gambit",
    "Queen's Gambit Refused: Chigorin Defense, Tartakower Gambit",
    'Modern Defense: Neo-Modern Defense',
    'Italian Game: Scotch Gambit, de Riviere Defense',
    'Sicilian Defense: Scheveningen Variation, English Attack #2',
    'Old Indian: Czech Variation',
    'Alekhine Defense #3',
    "King's Indian Defense: Fianchetto Variation, Simagin Variation",
    'Alekhine Defense: Mokele Mbembe, Vavra Defense',
    "Queen's Gambit Accepted: Central Variation, Alekhine System",
    "English Opening: King's English Variation, Two Knights Variation, Smyslov System",
    'Sicilian Defense: Smith-Morra Gambit Accepted, Taimanov Formation',
    'Sicilian Defense: Najdorf Variation, English Attack, Anti-English',
    'Slav Defense: Suechting Variation',
    'Russian Game: Stafford Gambit',
    'Ruy Lopez: Closed Variations, Closed Defense',
    'Ruy Lopez: Closed, Anti-Marshall 8.a4',
    'Englund Gambit Complex: Mosquito Gambit',
    "Queen's Pawn Game: Torre Attack, Gruenfeld Variation",
    'Scotch Gambit',
    'French Defense: Classical Variation, Svenonius Variation',
    'Center Game Accepted',
    'Ruy Lopez: Morphy Defense, Norwegian Variation',
    'Ruy Lopez: Lucena Variation',
    "King's Gambit Accepted, Muzio Gambit, Sarratt Defense",
    'English Opening: Jaenisch Gambit',
    "Bird Opening: From's Gambit, Lasker Variation",
    'Semi-Slav Defense: Quiet Variation #2',
    'Amazon Attack: Siberian Attack',
    "Bishop's Opening: McDonnell Gambit",
    "King's Gambit Accepted, Stamma Gambit",
    'Philidor Defense: Hanham Variation, Delmar Variation',
    'Torre Attack: Classical Defense, Nimzowitsch Variation',
    "Bishop's Opening: Lewis Gambit",
    "King's Indian Defense: Semi-Averbakh System",
    "King's Pawn Game: Schulze-Mueller Gambit",
    "King's Gambit Accepted, Philidor Gambit",
    'Old Indian Defense: Tartakower-Indian',
    'Ruy Lopez: Closed Variations, Pilnik Variation',
    'Nimzo-Indian Defense: Huebner Variation',
    "King's Gambit Accepted, Allgaier Gambit",
    'Bogo-Indian Defense: Nimzowitsch Variation',
    "Queen's Pawn Game: Veresov Attack, Two Knights System, Gruenfeld Defense",
    "King's Gambit Accepted, Lolli Gambit",
    'Sicilian Defense: Scheveningen Variation, Tal Variation',
    "Queen's Indian Defense: Riumin Variation",
    "Queen's Gambit Accepted: Bogoljubov Defense",
    'Polish Opening: Birmingham Gambit',
    'French Defense: Rubinstein Variation, Ellis Gambit',
    'Budapest Defense: Alekhine Variation, Abonyi Variation',
    "Queen's Indian Defense: Classical Variation, Traditional Variation, Nimzowitsch Line",
    'Sicilian Defense: Dragon Variation, Yugoslav Attack, Old Line',
    'Italian Game: Evans Gambit, Anderssen Defense',
    "King's Pawn Game: Weber Gambit",
    "King's Indian Defense: Saemisch Variation, Yates Defense",
    'Ruy Lopez: Exchange Variation, Alapin Gambit',
    'Owen Defense: Naselwaus Gambit',
    'French Defense: Advance Variation, Lputian Variation',
    'Modern Defense: Gurgenidze Defense',
    'Nimzo-Indian Defense: 4.e3 e8g8, 5.Nf3, without ...d5',
    'Zukertort Defense: Sicilian Knight Variation',
    'Gruenfeld Defense: Three Knights Variation, Hungarian Attack',
    "King's Gambit Accepted, Bishop's Gambit, Lopez Defense",
    'Benoni Defense: Pawn Storm Variation',
    'Gruenfeld Defense: Russian Variation, Accelerated Variation',
    'Blackmar-Diemer Gambit: Tartakower Variation',
    'French Defense: Winawer Variation, Bogoljubov Variation',
    "King's Gambit Accepted, Kieseritzky Gambit, Long Whip",
    'Van Geet Opening: Sicilian Two Knights',
    'Lion Defense: Anti-Philidor',
    'Pirc Defense: Austrian Attack',
    'Ruy Lopez: Exchange Variation, Romanovsky Variation',
    'Sicilian Defense: Wing Gambit, Abrahams Variation',
    'Italian Game: Classical Variation, Greco Gambit, Main Line',
    "Petrov's Defense #3",
    'Catalan Opening: Closed Variation, Traditional Variation',
    "King's Indian Defense: Normal Variation, Standard Development",
    'Scotch Game: Vitzthum Attack',
    'Ruy Lopez: Closed Variations, Rosen Attack',
    'Sicilian Defense: Paulsen Variation, Szen Variation',
    'Ruy Lopez: Morphy Defense, Mackenzie Variation',
    'Sicilian Defense: Smith-Morra Gambit Accepted, Chicago Defense',
    "Queen's Gambit Accepted: Schwartz Defense",
    'Sicilian Defense: Dragon Variation, Modern Bc4 Variation',
    "Blackmar-Diemer Gambit Declined, O'Kelly Defense",
    'Sicilian Defense: Kan Variation, Maroczy Bind, Bronstein Variation',
    "Queen's Gambit Declined: Janowski Variation",
    'Bogo-Indian Defense: Gruenfeld Variation',
    'Ruy Lopez: Marshall Attack, Main Line',
    "King's Gambit: Panteldakis Countergambit, Greco Variation",
    'Blackmar-Diemer Gambit Declined, Lamb Defense',
    'Caro-Kann Defense: Finnish Variation',
    'Vienna Game: Vienna Gambit, Modern Variation',
    "Queen's Gambit Accepted: Classical Defense",
    'French Defense: Baeuerle Gambit',
    "King's Gambit Accepted, Kieseritzky Gambit, Cotter Gambit",
    'Nimzo-Indian Defense: Normal Variation, Gligoric System, Exchange at c4',
    'Tarrasch Defense: Classical Variation, Main Line',
    'French Defense: Classical Variation, Burn Variation, Main Line',
    'Ruy Lopez: Berlin Defense, Tarrasch Trap',
    'Reti Opening: Reti Gambit, Keres Variation',
    'Neo-Gruenfeld Defense: Classical Variation, Polgar Variation',
    'Benoni Defense: Fianchetto Variation',
    'Nimzo-Larsen Attack: Spike Variation',
    'Sicilian Defense: Grand Prix Attack, Schofman Variation',
    'Four Knights Game: Spanish Variation, Rubinstein Variation Accepted',
    'Ruy Lopez: Schliemann Defense, Tartakower Variation',
    'Modern Defense: Wind Gambit',
    'English Opening: Agincourt Defense, Kurajica Defense',
    "Sicilian Defense: O'Kelly Variation, Maroczy Bind, Paulsen Line",
    'Pirc Defense: Classical Variation, Quiet System, Chigorin Line',
    'Italian Game: Evans Gambit, Mieses Defense',
    "King's Indian Defense: Fianchetto Variation, Classical Main Line",
    'Ruy Lopez: Morphy Defense, Breyer Defense, Zaitsev Hybrid',
    "Queen's Gambit Accepted: Alekhine Defense",
    'Bird Opening: Lasker Variation',
    'Sicilian Defense: Alapin Variation, Sherzer Variation',
    'Italian Game: Evans Gambit, Mayet Defense',
    'Alekhine Defense: Krejcik Variation, Krejcik Gambit',
    "Queen's Gambit Refused: Albin Countergambit, Fianchetto Variation",
    'Ruy Lopez: Closed Variations, Delayed Exchange',
    "King's Indian Defense: Orthodox Variation, Donner Defense",
    "King's Indian Defense: Averbakh Variation, Geller Defense",
    "King's Gambit, Falkbeer Countergambit, Charousek Gambit Accepted",
    "King's Indian Defense: Orthodox Variation, Classical System, Benko Attack",
    'Caro-Kann Defense: Forgacs Variation',
    "King's Indian Attack: Sicilian Variation #2",
    'Four Knights Game: Rubinstein Countergambit, 5.Be2',
    'French Defense: Rubinstein Variation, Fort Knox Variation',
    'Ruy Lopez: Cozio Defense, Paulsen Variation',
    'Italian Game: Two Knights Defense, Lolli Attack',
    'English Opening: Anglo-Indian Defense, Flohr-Mikenas-Carls Variation, Nei Gambit',
    'Philidor Defense: Hanham Variation, Krause Variation',
    'Sicilian Defense: Najdorf Variation, Polugaevsky Variation',
    'Grob Opening: Double Grob',
    'Ruy Lopez: Open Variations, Riga Variation',
    "King's Indian Defense: Fianchetto Variation, Larsen Defense",
    'Nimzowitsch Defense: Kennedy Variation, Keres Attack',
    "King's Gambit, Falkbeer Countergambit, Charousek Gambit, Morphy Defense",
    "Sicilian Defense: O'Kelly Variation, Quiet System",
    "Queen's Gambit Declined: Tartakower Defense",
    "Queen's Gambit Refused: Albin Countergambit, Modern Line",
    'English Opening: Symmetrical Variation, Botvinnik System Reversed',
    'Sicilian Defense: Kupreichik Variation',
    'English Opening: Symmetrical Variation, Duchamp Variation',
    'Sicilian Defense: Najdorf Variation, Poisoned Pawn Variation',
    "Queen's Pawn Game: Veresov Attack, Anti-Veresov",
    'Doery Defense',
    'Sicilian Defense: Classical Variation, Fianchetto Variation',
    'French Defense: Tarrasch Variation, Guimard Defense',
    'Valencia Opening',
    'Pterodactyl Defense: Eastern, Pteranodon',
    'Ruy Lopez: Open Variations, Open Variation',
    'Philidor Defense: Lion Variation, Bishop Sacrifice',
    "Ruy Lopez: Berlin Defense, l'Hermet Variation",
    'Nimzo-Indian Defense: Classical, Noa Variation, 5.cxd5 exd5',
    'Four Knights Game: Marshall Variation',
    'Nimzowitsch Defense: El Columpio Defense',
    'Nimzo-Indian Defense: Kmoch Variation',
    "King's Gambit Accepted: Soerensen Gambit",
    "English Opening: King's English Variation, Two Knights Variation, Fianchetto Line",
    'Center Game: Kieseritzky Variation',
    "King's Indian Defense: Orthodox Variation, Aronin-Taimanov Defense",
    'Ruy Lopez: Columbus Variation',
    "Bishop's Opening: Boden-Kieseritzky Gambit",
    'Blackmar-Diemer Gambit: Pietrowsky Defense',
    'Caro-Kann Defense: Exchange Variation, Rubinstein Variation',
    'Ruy Lopez: Morphy Defense, Arkhangelsk Variation',
    'Scandinavian Defense: Classical Variation',
    'French Defense: Winawer Variation, Advance Variation, Moscow Variation',
    'Blackmar-Diemer Gambit: Lemberger Countergambit, Simple Variation',
    'Sicilian Defense: Grob Variation',
    'Hungarian Opening: Van Kuijk Gambit',
    "Queen's Gambit Accepted: Mannheim Variation",
    'Crab Opening',
    'Sicilian Defense: Nyezhmetdinov-Rossolimo Attack, Fianchetto Variation, Lutikov Gambit',
    'Latvian Gambit: Mayet Attack',
    'Nimzo-Indian Defense: Reshevsky Variation',
    'Slav Defense: Breyer Variation',
    'English Opening: Anglo-Indian Defense, Slav Formation',
    'Neo-Gruenfeld Defense: Delayed Exchange Variation',
    'Ruy Lopez: Alapin Defense',
    "Queen's Pawn Game: Levitsky Attack, Euwe Variation, Modern Line",
    "Queen's Gambit Refused: Baltic Defense, Queen Attack Deferred",
    'Modern Defense: Averbakh Variation, Pseudo-Saemisch',
    'Sicilian Defense: Smith-Morra Gambit Declined, Dubois Variation',
    "Queen's Gambit Declined: Lasker Defense",
    'Nimzo-Indian Defense: Normal Variation',
    'Pirc Defense: Classical Variation, Quiet System, Czech Defense',
    'Philidor Defense: Nimzowitsch Variation, Rellstab Variation',
    'Sicilian Defense: Accelerated Dragon, Modern Bc4 Variation',
    "King's Indian Defense: Zinnowitz Variation",
    'Ruy Lopez: Classical Variation, Konikowski Gambit',
    "King's Indian Defense: Saemisch Variation, Bobotsov-Korchnoi-Petrosian Variation",
    'Ponziani Opening: Romanishin Variation',
    'Blackmar-Diemer Gambit: Bogoljubov Variation',
    "King's Indian Defense: Fianchetto Variation, Kavalek Defense",
    'Ruy Lopez: Classical Variation, Zukertort Gambit',
    'St. George Defense: New St. George, Traditional Line',
    'Nimzo-Indian Defense: Normal Variation, Saemisch Deferred',
    'Ruy Lopez: Berlin Defense, Fishing Pole Variation',
    'Blackmar-Diemer Gambit: Bogoljubov Variation, Kloss Attack',
    "King's Indian Defense: Four Pawns Attack, Modern Defense",
    "King's Gambit Accepted: Cunningham, Bertin Gambit",
    "King's Gambit Accepted, Bishop's Gambit, Bledow Countergambit",
    'Sicilian Defense: Najdorf Variation, Traditional Line',
    "Queen's Indian Defense: Classical Variation, Traditional Variation",
    'Semi-Slav Defense: Noteboom Variation, Anti-Noteboom Variation',
    'Ruy Lopez: Morphy Defense, Graz Variation',
    'Ruy Lopez: Closed Variations, Averbakh Variation',
    "King's Indian Defense: Averbakh Variation, Nc6 Defense",
    'Gruenfeld Defense: Three Knights Variation, Burille Variation, Reversed Tarrasch',
    "Queen's Indian Defense: Euwe Variation",
    'French Defense: Winawer Variation, Poisoned Pawn Variation',
    'Polish Opening: Tartakower Gambit',
    "King's Gambit Accepted, Muzio Gambit, Wild Muzio Gambit",
    'Nimzo-Indian Defense: Classical Variation, Keres Defense',
    'Scotch Game: Paulsen Attack',
    'Pterodactyl Defense: Fianchetto, Queen Benoni Pterodactyl',
    'Pirc Defense: Austrian Attack, Unzicker Attack',
    'Italian Game: Rosentreter Gambit',
    'Scotch Game: Scotch Gambit, Cochrane-Anderssen Variation',
    'Sicilian Defense: Sozin Attack, Main Line',
    'Scandinavian Defense: Richter Variation',
    'English Opening: Myers Variation',
    "Sicilian Defense: O'Kelly Variation, Venice System, Steiner Line",
    'Italian Game: Two Knights Defense, Traxler Counterattack',
    'Kadas Opening: Kadas Gambit #3',
    'Nimzowitsch Defense: French Connection',
    'Four Knights Game: Scotch Variation, Belgrade Gambit',
    'Indian Game: Gibbins-Wiedenhagen Gambit Accepted',
    "King's Indian Defense: Fianchetto Variation, Delayed Fianchetto",
    "Queen's Pawn Game: Torre Attack, Gruenfeld Variation, Main Line",
    "King's Indian Attack: Omega-Delta Gambit",
    'Benoni Defense: Modern Variation, Snake Variation',
    'Semi-Slav Defense: Meran Variation, Wade Variation',
    'Caro-Kann Defense: Panov Attack, Fianchetto Defense',
    "King's Indian Defense: Saemisch Variation, Closed Variation",
    'Nimzo-Indian Defense: Normal Variation, Taimanov Variation',
    'Sicilian Defense: Najdorf Variation, Scheveningen Variation',
    'Sicilian Defense: Paulsen Variation, Taimanov Variation',
    "Queen's Gambit Refused: Marshall Defense, Tan Gambit",
    'French Defense: Alekhine-Chatard Attack, Albin-Chatard Gambit',
    'Englund Gambit Declined, Reversed Mokele Mbembe',
    'Italian Game: Giuoco Piano',
    'Zukertort Opening: Herrstrom Gambit',
    'Gruenfeld Defense: Three Knights Variation, Hungarian Variation',
    'Polish Opening: Wolferts Gambit',
    'Semi-Slav Defense: Stoltz Variation, Shabalov Attack',
    'French Defense: Alekhine-Chatard Attack',
    'English Opening: Agincourt Defense, Catalan Defense',
    'Van Geet Opening: Battambang Variation',
    'Semi-Slav Defense: Romih Variation',
    'Ruy Lopez: Morphy Defense, Chigorin Defense, Panov System',
    'Englund Gambit Complex: Stockholm Variation',
    "King's Indian Defense: Saemisch Variation, Double Fianchetto",
    'Nimzo-Larsen Attack: Graz Attack',
    "Queen's Gambit Declined: Modern, Knight Defense #3",
    "English Opening: Anglo-Indian Defense, Queen's Indian Formation",
    'Nimzo-Indian Defense: Normal Variation, Huebner Deferred',
    'Sicilian Defense: Brick Variation',
    'Nimzowitsch Defense: Scandinavian Variation',
    "Queen's Gambit Accepted: Godes Variation",
    'English Opening: Anglo-Indian Defense, Anglo-Gruenfeld Variation',
    'Ruy Lopez: Closed, 7...O-O',
    'Sicilian Defense: Dragon Variation, Yugoslav Attack, Belezky Line',
    'Russian Game: Kaufmann Attack',
    "Queen's Gambit Refused: Chigorin Defense, Lazard Gambit",
    "Polish Opening: Queen's Indian Variation",
    'French Defense: Winawer Variation, Winckelmann-Riemer Gambit',
    'Italian Game: Scotch Gambit Declined #2',
    'Scotch Game: Alekhine Gambit',
    'Sicilian Defense: Lasker-Pelikan Variation, Sveshnikov Variation',
    'Sicilian Defense: Classical Variation, Anti-Sozin Variation',
    "King's Gambit Declined: Falkbeer, Rubinstein Variation",
    "Sicilian Defense: O'Kelly Variation, Wing Gambit",
    'Indian Game: Gedult Attack, Gedult Attack',
    'Caro-Kann Defense: Mieses Gambit',
    "King's Indian Attack: Double Fianchetto",
    'Benko Gambit Accepted, Fianchetto Variation',
    'Ruy Lopez: Berlin Defense: Mortimer Variation',
    'English Opening: Mikenas-Carls Variation #3',
    'French Defense: Tarrasch Variation, Guimard Defense, Main Line',
    "King's Indian Defense: Fianchetto Variation, Lesser Simagin (Spassky)",
    'Robatsch Defense',
    'Caro-Kann Defense: Two Knights Attack, Mindeno Variation, Exchange Line',
    "Sicilian Defense: O'Kelly Variation, Venice System, Gambit Line",
    'Ruy Lopez: Schliemann Defense, Exchange Variation',
    'Italian Game: Evans Gambit Declined, 5.a4',
    'Sicilian Defense: Snyder Variation, Queen Fianchetto Variation',
    'Sicilian Defense: Dragon, Classical, Grigoriev Variation',
    'Italian Game: Rousseau Gambit',
    'English Opening: Wing Gambit',
    'Ruy Lopez: Bird Variation, Paulsen Variation',
    'French Defense: Winawer Variation, Alekhine Gambit Accepted',
    "King's Pawn Game: Tayler Opening, Inverted Hanham",
    'Caro-Kann Defense: Classical Variation, Seirawan Variation',
    'Dutch Defense: Leningrad Variation, Warsaw Variation',
    "English Opening: King's English Variation, Closed System",
    'Mikenas Defense: Cannstatter Variation',
    'Sicilian Defense: Modern Variations',
    "King's Gambit, Falkbeer Countergambit, Pickler Gambit",
    'Benoni Defense: Mikenas Variation',
    "Queen's Pawn Game: Englund Gambit",
    'Italian Game: Two Knights Defense, Paoli Variation',
    "Queen's Gambit Declined: Neo-Orthodox Variation",
    'Sicilian Defense: Dragon Variation, Classical Variation, Normal Line',
    "King's Pawn Opening: Speers",
    'Ruy Lopez: Classical Variation, Charousek Variation',
    'Hungarian Opening: Myers Defense',
    'Russian Game: Modern Attack',
    'Caro-Kann Defense: Gurgenidze System',
    'Nimzo-Indian Defense: Normal Variation, Bishop Attack, Classical Defense',
    'Scotch Game: Goering Gambit, Bardeleben Variation',
    'St. George Defense: San Jorge Variation',
    'Hippopotamus Defense',
    'English Opening: Agincourt Defense, Wimpy System',
    'French Defense: Classical Variation, Normal Variation',
    'Sicilian Defense: Accelerated Dragon, Maroczy Bind, Gurgenidze Variation',
    "King's Gambit, Falkbeer Countergambit, Modern Transfer",
    "Queen's Indian Defense: Classical Variation, Traditional Variation, Main Line",
    "Queen's Gambit Declined: Alapin Variation",
    'St. George Defense: Woodchuck Variation',
    'Sicilian Defense: Yates Variation',
    'Vienna Game: Fyfe Gambit',
    "Bishop's Opening: Vienna Hybrid, Hromadka Variation",
    'Englund Gambit Declined, Reversed Brooklyn',
    'French Defense: Franco-Hiva Gambit II',
    "Queen's Indian Defense: Petrosian Variation",
    'St. George Defense: New St. George, Sanky-George Gambit',
    'Benoni Defense: Four Pawns Attack',
    'Caro-Kann Defense: Alekhine Gambit',
    'Trompowsky Attack: Poisoned Pawn Variation',
    'Ruy Lopez: Exchange Variation, Alekhine Variation',
    'French Defense: Bird Invitation',
    'Reti Opening: Anglo-Slav Variation, Bogoljubov Variation, III',
    'Caro-Kann Defense: Panov Attack, Modern Defense, Carlsbad Line',
    'Gruenfeld Defense: Brinckmann Attack',
    'Sicilian Defense: Nimzowitsch Variation, Exchange Variation',
    'Sicilian Defense: Richter-Rauzer Variation',
    'Modern Defense: Semi-Averbakh Variation, Pterodactyl Variation Accepted',
    'Sicilian Defense: Smith-Morra Gambit Declined, Center Formation',
    'Dutch Defense: Janzen-Korchnoi Gambit',
    'Sicilian Defense: Najdorf Variation, Main Line',
    'Scotch Game: Scotch Gambit, Kingside Variation',
    "King's Indian Defense: Averbakh Variation",
    "Queen's Indian Defense: Fianchetto Variation, Saemisch Variation",
    'Ruy Lopez: Closed Variations, Worrall Attack, Delayed Castling Line',
    'Old Indian Defense: Janowski Variation, Fianchetto Variation #2',
    'Sicilian Defense: Flohr Variation',
    'Semi-Slav Defense: Botvinnik System',
    'French Defense: MacCutcheon, Advance Variation',
    'Trompowsky Attack: Borg Variation',
    'Irish Gambit',
    "King's Indian Defense: Fianchetto Variation, Double Fianchetto Attack",
    'Italian Game: Scotch Gambit',
    "King's Gambit Declined: Falkbeer, Milner-Barry Variation",
    'Ruy Lopez: Schliemann Defense, Dyckhoff Variation',
    "King's Gambit Accepted, Ghulam-Kassim Gambit",
    "King's Indian Defense: Four Pawns Attack, Fluid Attack",
    'French Defense: Winawer Variation, Alekhine-Maroczy Gambit',
    "King's Indian Defense: Fianchetto Variation, Yugoslav System, without Nc3",
    'Modern Defense: Fianchetto Gambit',
    'Slav Defense: Steiner Variation',
    'Rubinstein Opening: Classical Defense',
    "King's Gambit Accepted, Bishop's Gambit, Bogoljubov Defense",
    'Polish Opening: Bugayev Advance Variation',
    'Semi-Slav Defense: Gunderam Gambit',
    'Bird Opening: Mujannah',
    'Sicilian Defense: McDonnell Attack, Tal Gambit',
    'Caro-Kann Defense: Maroczy Variation, Maroczy Gambit',
    'Russian Game: Modern Attack, Center Attack',
    "Queen's Pawn Game: Veresov Attack, Richter Variation",
    'Sicilian Defense: Brussels Gambit',
    'Sicilian Defense: Alapin Variation, Barmen Defense, Modern Line',
    "King's Indian Attack: Spassky Variation",
    'Latvian Gambit: Fraser Defense',
    "Bishop's Opening: Warsaw Gambit",
    'Modern Defense: Averbakh System, Randspringer Variation',
    "Queen's Gambit Refused: Baltic Defense, Pseudo-Chigorin",
    "Queen's Gambit Declined: Harrwitz Attack, Two Knights Defense, Blockade Line",
    'Caro-Kann Defense: Hector Gambit',
    "King's Pawn Game: Damiano Defense, Damiano Gambit, Chigorin Gambit",
    'English Opening: Symmetrical Variation, Three Knights Variation',
    'Scandinavian Defense: Schiller-Pytel Variation',
    'Slav Defense: Exchange Variation, Symmetrical Line',
    'Vienna Game: Vienna Gambit, Breyer Variation',
    "King's Indian Defense: Four Pawns Attack, Normal Attack",
    'Zukertort Opening: Arctic Defense, Drunken Knight Variation',
    'Russian Game: Classical Attack, Staunton Variation',
    'Caro-Kann Defense: Panov Attack, Gunderam Attack',
    'English Opening: Anglo-Indian Defense, Anti-Anti-Gruenfeld',
    "Queen's Gambit Declined: Semi-Tarrasch, San Sebastian Variation",
    "Queen's Gambit Accepted: Classical Defense, Main Line",
    'Neo-Gruenfeld Defense: Goglidze Attack',
    'Sicilian Defense: Kveinis Variation',
    'Italian Game: Two Knights Defense, Steinitz Variation',
    'Sicilian Defense: Smith-Morra Gambit Accepted, Morphy Defense',
    "Queen's Gambit Declined: Tartakower Defense, Makogonov Exchange Variation",
    'French Defense: Winawer Variation, Maroczy-Wallis Variation',
    'Benoni Defense: Four Pawns Attack, Main Line',
    'Sicilian Defense: Smith-Morra Gambit Accepted, Kan Formation',
    'Alekhine Defense: Four Pawns Attack, Fianchetto Variation',
    "Queen's Gambit Declined: Alekhine Variation",
    "King's Gambit Accepted, Fischer Defense, Spanish Variation",
    'Ruy Lopez: Closed Variations, Kholmov Variation',
    'English Opening: Agincourt Defense, Keres Defense',
    'Bird Opening: Dutch Variation, Batavo Gambit',
    "Polish Opening: King's Indian Variation, Schiffler Attack",
    'Nimzowitsch Defense: Neo-Mongoloid Defense',
    'Dutch Defense: Leningrad Variation',
    'Three Knights Opening: Schlechter Variation',
    'Four Knights Game: Nimzowitsch (Paulsen)',
    'Ruy Lopez: Retreat Variation',
    "English Opening: King's English Variation, Four Knights Variation #2",
    "Sicilian Defense: O'Kelly Variation, Normal System, Smith-Morra Line",
    'Dutch Defense: Staunton Gambit Accepted',
    'Zukertort Opening: Basman Defense',
    "Queen's Indian Defense: Kasparov-Petrosian Variation, Classical Variation",
    'Sicilian Defense: Dragon Variation, Classical Variation #2',
    'Sicilian Defense: Richter-Rauzer Variation, Modern Variation',
    'Sicilian Defense: Smith-Morra Gambit Accepted, Pin Defense',
    "King's Gambit Accepted, Double Muzio Gambit, Bello Gambit",
    "Queen's Gambit Declined: Modern Variation, Heral Variation",
    "Zukertort Opening: Santasiere's Folly",
    'Latvian Gambit: Mayet Attack, Polerio-Svedenborg Variation',
    'Italian Game: Evans Gambit, McDonnell Defense, Main Line',
    'Italian Game: Scotch Gambit, Max Lange Attack',
    'Sicilian Defense: Richter-Rauzer, 6...e6',
    'Four Knights Game: Spanish Variation, Symmetrical Variation #3',
    'French Defense: MacCutcheon Variation, Tartakower Variation',
    'Pirc Defense: Austrian Attack #2',
    "King's Gambit Accepted, Bishop's Gambit, Gianutio Gambit",
    'Bird Opening: Dutch Variation, Dudweiler Gambit',
    'Italian Game: Evans Gambit, Anderssen Variation',
    'Italian Game: Evans Gambit, Dufresne Defense',
    "Queen's Gambit Declined: Modern, Knight Defense #2",
    "Ruy Lopez: Bird's Defense Deferred",
    'Hungarian Opening: Buecker Gambit',
    'Ruy Lopez: Closed Variations, Morphy Attack',
    'Philidor Defense: Hanham Variation, Steiner Variation',
    'Ruy Lopez: Exchange, Alekhine Variation',
    'Ruy Lopez: Closed, Breyer, 10.d4',
    'Hungarian Opening: Dutch Defense',
    'Slav Defense: Czech Variation, Classical System, Main Line',
    'Sicilian Defense: Big Clamp Formation',
    'Dutch Defense: Alapin Variation',
    'Italian Game: Classical Variation, Closed Variation',
    'Sicilian Defense: Accelerated Dragon, Maroczy Bind, Breyer Variation',
    "Queen's Pawn Game: Zurich Gambit",
    'French Defense: MacCutcheon Variation',
    'English Opening: Mikenas-Carls, Sicilian',
    'French Defense: Winawer Variation, Advance Variation #2',
    "Queen's Gambit Accepted: Classical Defense, Alekhine System (Except Main Line)",
    'Vienna Game: Vienna Gambit, Main Line',
    'Gruenfeld Defense: Smyslov Defense',
    'French Defense: Advance Variation, Nimzowitsch Attack',
    'French Defense: Classical Variation, Tarrasch Variation',
    'French Defense: Advance Variation, Nimzowitsch Gambit',
]

opening_to_bits: dict[str, bitLib.bitarray] = {
    s: bitLib.bitarray(format(i, f'0{OPENING_BITS}b'))
    for i, s in enumerate(_OPENING_STRINGS)
}
opening_to_bits["UNKNOWN_TEXT"] = bitLib.bitarray(
    format(OPENING_UNKNOWN, f"0{OPENING_BITS}b")
)

bits_to_opening: dict[str, str] = {v.to01(): k for k, v in opening_to_bits.items()}
